### ISSUE TITLE
Old-network-config installation sets subnetwork address as bridge address

### ISSUE THREAD

**Issue by skonefal** [eparis/kubernetes-ansible#11]
Hello,

In Dec 10 I have raised an issue on Kubernetes repository about ansible scripts. It was accepted and triaged... but recently I saw, that I have raised it in wrong repository ;)

Issue link: https://github.com/GoogleCloudPlatform/kubernetes/issues/2826

I wanted to prepare fix and post pull-request, but I didn't have CLA signed with Google. Now I see that you have refactored those scripts - does this issue is still actual? Or maybe you plan to remove 'old-*' configs later? 

Regards,
SK

**Comment by eparis** [comment]
it would need to be here, not there.  you should just close that one.  But I don't know how to do it in ansible...

I'm planning to keep those other network configs around for at least a while, but i'm not testing or using them any more...

**Comment by eparis** [comment]
i consider the old-* stuff deprecated, just use flannel   :)
