### ISSUE TITLE
Add a new node

### ISSUE THREAD

**Issue by sroze** [eparis/kubernetes-ansible#26]
Is it possible to add a minion (well, now node) to the cluster easily ? I'm thinking that running agin the `setup.yml` will break everything right ?

Oh yeah, and thank you very much for your work on that Ansible playbook !

**Comment by eparis** [comment]
We've worked really hard to make sure the playbook is idempotent. Obviously running it a second time will undo any manual changes you made after running it the first time. But running the playbook 2+ times should be perfectly fine and should always get you back to a nice clean running cluster.

However, now with the latest kube you don't need much config on the node. Copy /etc/kubernetes/* from some other node, update /etc/kubernetes/kubelet (to fix hostname_override) and you should be good to go...
