### ISSUE TITLE
kubernetes package not found by yum 

### ISSUE THREAD

**Issue by GiovanniPaoloGibilisco** [eparis/kubernetes-ansible#5]
the kubernetes package is not found in the default yum repositories, the updates-testing repositories must be added when tunning the fedora task in the kubernetes role, 
suggest to modify line:
yum: pkg=kubernetes state=latest 

in 
yum: pkg=kubernetes state=latest enablerepo=updates-testing

**Comment by eparis** [comment]
This should be in the default repos now.
